spring:
  main:
    # the banned is printed to the log; this requires the first line to be empty to avoid formatting issues
    banner-mode: log
  kafka:
    streams:
      # application id is typically overridden
      application-id: wikipedia
      properties:
        # the default Serdes define the data format contract
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
        # exactly_once_beta has improvements for group management, unlikely for change
        processing.guarantee: exactly_once_beta
        # behavioral settings, do not override
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
        default.production.exception.handler: org.apache.kafka.streams.errors.DefaultProductionExceptionHandler

        # target deployment settings to be overridden

        # replication factor of 1 is default setting for limited environments; in practice always 3
        replication.factor: 1

    bootstrap-servers:
      - localhost:9092
    properties:
      security.protocol: PLAINTEXT
      # Schema Registry address
      schema.registry.url: http://localhost:8081

wikipedia:
  topics:
    input: wikipedia.parsed
    output: wikipedia.parsed.count-by-domain
