spring:
  main:
    banner-mode: log
  kafka:
    streams:
      application-id: wikipedia
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
        processing.guarantee: exactly_once
        replication.factor: 1
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
        default.production.exception.handler: org.apache.kafka.streams.errors.DefaultProductionExceptionHandler
    bootstrap-servers:
      - localhost:9092
    properties:
      security.protocol: PLAINTEXT

wikipedia:
  topics:
    input: wikipedia.parsed
    output: wikipedia.parsed.count-by-domain
