# Template file with typical places for configuration
spring:
  kafka:
    streams:
      application-id: wikipedia
      properties:
        replication.factor: 1
    bootstrap-servers:
      - localhost:9092
    properties:
      security.protocol: PLAINTEXT

wikipedia:
  topics:
    input: wikipedia.parsed
    output: wikipedia.parsed.count-by-domain
